# Generated by Django 2.2.13 on 2022-05-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
