# Generated by Django 2.2.13 on 2022-05-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
